baseURL = "https://kinzel.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Blog of Guilherme Kinzel"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "\\.zip$"]

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Guilherme Kinzel"
author = "Guilherme Kinzel"
#copyright = "2020-2021"
description = "I'm GK!"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "mathjax"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/guilhermekinzel/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/Kinzel"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/guikinzel/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:guikinzel@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"
  
  [[menu.main]]
  name = "mt5R"
  weight = 300
  identifier = "mt5R"
  url = "/mt5R/"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"
  

#  [[menu.main]]
#  name = "Contact"
#  weight = 400
#  identifier = "contact"
#  url = "/contact/"